apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  # --- LOADBALANCER ---
  # This type tells Kubernetes to request an external IP address.
  # In your cluster, MetalLB will provide this IP.
  type: {{ .Values.service.type }}
  ports:
    - # --- Port 80 ---
      # This is the external port that users will connect to.
      port: {{ .Values.service.port }}
      # --- Target Port 8080 ---
      # This is the internal port on the pod where the gateway application is listening.
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}