spring:
  application:
    name: link-shortener-api-gateway
  config:
    import: "optional:configserver:http://link-shortener-config-server-dev-helm:8888,optional:file:/vault/secrets/secrets.yml"
  boot:
    admin:
      client:
        instance:
          service-base-url: http://${POD_IP:localhost}:8080