spring:
  application:
    name: link-shortener-api-gateway
  config:
    import: "optional:configserver:http://link-shortener-config-server-dev-helm:8888,optional:file:/vault/secrets/application.properties"
  boot:
    admin:
      client:
        url: http://link-shortener-spring-admin-dev-helm:8080