replicaCount: 1

spring:
  profiles:
    active: "dev"

ingress:
  hostname: "apidev.bpiatek.pl"

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"

vault:
  role: "link-shortener-api-gateway-dev-role"
  secretFiles:
    "secrets.yml":
      secretPath: "kv/data/dev/link-shortener-api-gateway/config"
      secretTemplate: |
        {{- with secret "kv/data/dev/link-shortener-api-gateway/config" -}}
        monitoring:
          user:
            name: {{ .Data.data.monitoring.user.name | quote }}
            password: {{ .Data.data.monitoring.user.password | quote }}
        {{- end -}}