replicaCount: 2

image:
  repository: link-shortener-api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  name: link-shortener-api-gateway

service:
  type: ClusterIP
  port: 80            # The external port (standard HTTP)
  targetPort: 8080    # The internal container port

ingress:
  hostname: "api.local"

spring:
  profiles:
    active: "default"

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0"
